#!/usr/bin/python3 -tt
import os
import urllib.request
import socket
import subprocess
import time 
import threading 
from queue import Queue
import nmap
print("""   
 █    ▄█    ▄     ▄       ▄      ▄███▄   █     ▄███▄   ▄█▄      ▄▄▄▄▀ █▄▄▄▄ ████▄    ▄      ▄▄▄▄▄   
 █    ██     █     █  ▀▄   █     █▀   ▀  █     █▀   ▀  █▀ ▀▄ ▀▀▀ █    █  ▄▀ █   █     █    █     ▀▄ 
 █    ██ ██   █ █   █   █ ▀      ██▄▄    █     ██▄▄    █   ▀     █    █▀▀▌  █   █ ██   █ ▄  ▀▀▀▀▄   
 ███▄ ▐█ █ █  █ █   █  ▄ █       █▄   ▄▀ ███▄  █▄   ▄▀ █▄  ▄▀   █     █  █  ▀████ █ █  █  ▀▄▄▄▄▀    
     ▀ ▐ █  █ █ █▄ ▄█ █   ▀▄     ▀███▀       ▀ ▀███▀   ▀███▀   ▀        █         █  █ █            
         █   ██  ▀▀▀   ▀                                               ▀          █   ██            
                                                                                                   
   """)
print ("1. Website Header Security Checker\n")
print ("2. Open Port Scanner\n")
print ("3. About\n")
print ("4. Exit\n")
main_input = int(input("Input Your Choice: "))
if main_input == 4:
 print("GoodBye...  :)")
 loop_condition = False
else:
  print("""
  --------------------------------------------------------------------------
  * Valid Url Example:- https://www.facebook.com/profile.php?id=100024869...*
                     :- https://www.youtube.com/channel/UC0XeF90vczK........*
                     :- https://mail.google.com/mail/u/0/#sent/Ktbx.........*
                     :- https://github.com/Dipenluitel/Linux-Electrons------*
  --------------------------------------------------------------------------
     """)
  url = input("Specify Valid Url:")
  print ("download starting!")
  input("Press Enter To download and Test The File:")
  filename, headers = urllib.request.urlretrieve(url, filename=Tested_Site)
  print ("download file location: ", filename)
  print ("download headers: ", headers)
  print ("Page download Sucessfully complete!")
  input("Press Enter To Exit") 
 elif main_input == 2:
  print("""
   ____            _   ____                                  
  |  _ \ ___  _ __| |_/ ___|  ___ __ _ _ __  _ __   ___ _ __ 
  | |_) / _ \| '__| __\___ \ / __/ _` | '_ \| '_ \ / _ \ '__|
  |  __/ (_) | |  | |_ ___) | (_| (_| | | | | | | |  __/ |   
  |_|   \___/|_|   \__|____/ \___\__,_|_| |_|_| |_|\___|_|  
    
  *-------------------------------------------------------*
  *             Host Name:- Enter Valid URL               *
  *                      :- www.google.com                *
  *             Port Num:-  0 to 1023                     * 
  *-------------------------------------------------------*
  """)
  print("Wait Few Minutes, Reading all open Ports... ")
  socket.setdefaulttimeout(0.55)
  print_lock = threading.Lock()
  target = input('Host to Scan: ')
  t_IP = socket.gethostbyname(target)
  print ('Scanning Host for Open Ports: ', t_IP)
  def portscan(port):
   s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
   try:
    conx = s.connect((t_IP, port))
    with print_lock:
      print(port, 'is open')
    conx.close()
   except:
      pass
  def threader():
   while True:
      worker = q.get()
      portscan(worker)
      q.task_done()     
  q = Queue()
  startTime = time.time()  
  for x in range(200):
   t = threading.Thread(target = threader)
   t.daemon = True
   t.start() 
  for worker in range(1, 65535):
   q.put(worker) 
  q.join()
  runtime = float("%0.2f" % (time.time() - startTime))
  print("Run Time: ", runtime, "seconds")
  input("Press Enter To Exit")
 elif main_input == 3:
  print("\nFacebook:- https://www.facebook.com/LinuxElectrons/")
  print("\nYoutube:-  https://www.youtube.com/channel/UC0XeF90vczKQOCXBlu6lMfA/")
  print("\nBlogspot:- Https://www.linuxElectrons.blogspot.com/")
  print("\nExecuted with Python3")
  input("\nPress Enter For Menu")
